name: Build and Test

on:
  push:
    branches: [ main ]
    paths-ignore: [ '**.md' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**.md' ]

env:
  BUILD_TYPE: Debug

jobs:
  build-desktop:
    if: ${{ false }}  # disable for now
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      working-directory: ${{github.workspace}}/test
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/test
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/test
      run: ctest --test-dir build -C ${{env.BUILD_TYPE}} --verbose

  build-emscripten:
    runs-on: ubunutu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: 3.1.34
        actions-cache-folder: 'emsdk-cache'
    
    - name: Configure CMake
      working-directory: ${{github.workspace}}/test
      run: emcmake cmake -B build/emscripten -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/test
      run: cmake --build build/emscripten --config ${{env.BUILD_TYPE}}
