name: Build and Test

on:
  push:
    branches: [ main ]
    paths-ignore: [ '**.md' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**.md' ]

env:
  BUILD_TYPE: Debug

jobs:
  build-desktop:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      working-directory: ${{github.workspace}}/test
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/test
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/test
      run: ctest --test-dir build -C ${{env.BUILD_TYPE}} --verbose

  build-emscripten:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Emscripten SDK
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: 3.1.34
        actions-cache-folder: 'emsdk-cache'
    
    - name: Configure CMake
      working-directory: ${{github.workspace}}/test
      run: emcmake cmake -B build/emscripten -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/test
      run: cmake --build build/emscripten --config ${{env.BUILD_TYPE}}

  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Android NDK
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
        add-to-path: false
        
    - name: Configure CMake
      working-directory: ${{github.workspace}}/test
      env:
        ANDROID_NDK_HOME: ${{steps.setup-ndk.outputs.ndk-path}}
      run: cmake -B build/android -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{env.ANDROID_NDK_HOME}}/build/cmake/android.toolchain.cmake

    - name: Build
      working-directory: ${{github.workspace}}/test
      run: cmake --build build/android --config ${{env.BUILD_TYPE}}
